[server]
port = 8080
targetUrl = 

[udp]
;ip = 
port = 8089

[osc]
;ip = 
;port = 

[curl]
;ip = 127.0.0.1
;port = 7000

[player]
mode = WALL
left=0
top=0
width=1920
height=1080
fullscreen=true
alwaysTop=false
mouse=show
webViewZoom=1
mouseHook=false
resetTime=90
